### ISSUE TITLE
Support for Flux new annotation and label.

### ISSUE THREAD

**Issue by lukasmrtvy** [alexmt/argocd-flux#2]
Flux is adding ( https://github.com/fluxcd/flux/issues/2874
 ) label ( `fluxcd.io/sync-gc-mark`  ) and annotation ( `fluxcd.io/sync-checksum` ) to every resource now.
https://github.com/fluxcd/flux/blob/master/pkg/cluster/kubernetes/sync.go#L38
https://github.com/fluxcd/flux/blob/master/pkg/cluster/kubernetes/sync.go#L41

Would be nice to update argocd-flux for support of this type of metadata. ( Argo is always out of sync , after flux auto release )

I tried to add ( as a quick workaround ):
```
  ignoreDifferences:
  - kind: Namespace
    jsonPointers:
    - /metadata/annotations/fluxcd.io~/sync-checksum
    - /metadata/labels/fluxcd.io~/sync-gc-mark
  - kind: Service
    jsonPointers:
    - /metadata/annotations/fluxcd.io~/sync-checksum
    - /metadata/labels/fluxcd.io~/sync-gc-mark
  - kind: Deployment
    jsonPointers:
    - /metadata/annotations/fluxcd.io~/sync-checksum
    - /metadata/labels/fluxcd.io~/sync-gc-mark
```
to application CRD, but without luck.

On the other side, Argo adds `app.kubernetes.io/instance` label, but it can be added via kustomization.yaml and commonLabels. ( Problem is that value must be known prior to deploy )

Thanks
